# Enable all endpoints
management.endpoints.web.exposure.include=*

# Base path for actuator endpoints (optional)
management.endpoints.web.base-path=/actuator

# Health endpoint config
management.endpoint.health.show-details=always

# Info endpoint custom data (optional)
info.app.name=@project.name@
info.app.version=@project.version@